version: '2'

services:
  mongodb:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    command: mongod

  logroundrobin:
    image: juancanon1725/logroundrobin:latest
    container_name: logroundrobin
    ports:
      - "35000:46000"

  logservices1:
    image: juancanon1725/logservices:latest
    container_name: logservices1
    ports:
     - "35001:46001"


  logservices2:
        image: juancanon1725/logservices:latest
        ports:
          - "35002:46001"
        container_name: logservices2

  logservices3:
        image: juancanon1725/logservices:latest
        ports:
          - "35003:46001"
        container_name: logservices3

volumes:
  mongodb:
  mongodb_config: